# Generated by Django 4.2.6 on 2023-11-07 12:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="Дата Рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications_discount",
            field=models.BooleanField(
                default=False, verbose_name="Получать уведомления о скидках"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications_favorite",
            field=models.BooleanField(
                default=False, verbose_name="Получать уведомления о товарах в избранном"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Мужской"), ("Female", "Женский")],
                max_length=50,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
