# Generated by Django 4.2.6 on 2023-11-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bot", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="categories",
            field=models.ManyToManyField(
                related_name="bots",
                through="bot.CategoryBot",
                to="categories.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AddField(
            model_name="bannercategory",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts_category",
                to="categories.category",
                verbose_name="Категория ботов",
            ),
        ),
    ]
