# Generated by Django 4.2.4 on 2023-09-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="is_special_offer",
            field=models.BooleanField(default=False, verbose_name="Спецпредложение"),
        ),
        migrations.AddField(
            model_name="bot",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1000, max_digits=8, verbose_name="Цена"
            ),
            preserve_default=False,
        ),
    ]
