# Generated by Django 4.2.4 on 2023-09-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_bot_is_special_offer_bot_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="example_photos",
                to="bot.bot",
                verbose_name="Бот",
            ),
        ),
    ]
