# Generated by Django 4.2.4 on 2023-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_photo_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="price",
            field=models.FloatField(verbose_name="Цена"),
        ),
    ]
