# Generated by Django 4.2.4 on 2023-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_alter_bot_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Цена"
            ),
        ),
    ]
