# Generated by Django 4.2.6 on 2023-10-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('bot', '0007_alter_bot_category_categorybot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybot',
            options={'verbose_name': 'Категории бота', 'verbose_name_plural': 'Категории ботов'},
        ),
        migrations.RemoveField(
            model_name='bot',
            name='category',
        ),
        migrations.AddField(
            model_name='bot',
            name='categories',
            field=models.ManyToManyField(related_name='bots', through='bot.CategoryBot', to='categories.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='categorybot',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='categorybot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория'),
        ),
    ]
