# Generated by Django 4.2.4 on 2023-11-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_categorybot_options_remove_bot_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='author_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка от автора'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Цена'),
        ),
    ]
