# Generated by Django 4.2.4 on 2023-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_bot_author_discount_alter_bot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='author_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Скидка от автора'),
        ),
    ]
