# Generated by Django 4.2.4 on 2023-11-01 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_bot_author_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='author_discount',
        ),
        migrations.CreateModel(
            name='DiscountAuthorBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_discount', models.DecimalField(decimal_places=0, default=0, help_text='Введите скидку от автора в процентах (от 0 до 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка от автора')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Скидка для бота',
                'verbose_name_plural': 'Скидки для ботов',
            },
        ),
    ]
