# Generated by Django 4.2.4 on 2023-11-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_bot_author_discount_discountauthorbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountauthorbot',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot', unique=True, verbose_name='Бот'),
        ),
    ]
