# Generated by Django 4.2.4 on 2023-11-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_discountauthorbot_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountauthorbot',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.bot', verbose_name='Бот'),
        ),
    ]
