# Generated by Django 4.2.4 on 2023-11-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_bot_author_discount_delete_botdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='author_discount',
        ),
        migrations.CreateModel(
            name='BotDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='bot.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Скидка на бота',
                'verbose_name_plural': 'Скидки на ботов',
            },
        ),
    ]
