# Generated by Django 4.2.4 on 2023-11-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_botdiscount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdiscount',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='bot.bot', unique=True, verbose_name='Бот'),
        ),
    ]
