# Generated by Django 4.2.4 on 2023-11-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_botdiscount_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdiscount',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='bot.bot', verbose_name='Бот'),
        ),
    ]
