# Generated by Django 4.2.6 on 2023-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0024_alter_botdiscount_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="count",
            field=models.IntegerField(default=1000, verbose_name="Количество"),
            preserve_default=False,
        ),
    ]
