# Generated by Django 4.2.4 on 2023-11-03 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_bannercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bannercategory',
            name='name',
        ),
        migrations.AddField(
            model_name='bannercategory',
            name='categorybot_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.categorybot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannercategory',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Введите скидку от автора в процентах (от 0 до 100).', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
    ]
