# Generated by Django 4.2.4 on 2023-11-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('bot', '0026_remove_bannercategory_id_remove_bannercategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercategory',
            options={'verbose_name': 'Скидка на бота', 'verbose_name_plural': 'Скидки на ботов'},
        ),
        migrations.RemoveField(
            model_name='bannercategory',
            name='categorybot_ptr',
        ),
        migrations.AddField(
            model_name='bannercategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannercategory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
