# Generated by Django 4.2.4 on 2023-11-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('bot', '0027_alter_bannercategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercategory',
            options={'verbose_name': 'Скидку на категорию ботов', 'verbose_name_plural': 'Скидки на категории ботов'},
        ),
        migrations.AlterField(
            model_name='bannercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_category', to='categories.category', verbose_name='Категория ботов'),
        ),
        migrations.AlterField(
            model_name='botdiscount',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_author', to='bot.bot', verbose_name='Бот'),
        ),
    ]
