# Generated by Django 4.2.4 on 2023-11-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('bot', '0028_alter_bannercategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botdiscount',
            options={'verbose_name': 'Скидка на бота от автора', 'verbose_name_plural': 'Скидки на ботов от авторов'},
        ),
        migrations.AlterField(
            model_name='bannercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_category', to='categories.category', unique=True, verbose_name='Категория ботов'),
        ),
    ]
