# Generated by Django 4.2.4 on 2023-11-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('bot', '0029_alter_botdiscount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercategory',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_category', to='categories.category', verbose_name='Категория ботов'),
        ),
    ]
