# Generated by Django 4.2.4 on 2023-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shopping_cart",
            constraint=models.UniqueConstraint(
                fields=("user", "bot"), name="unique_in_shopping_cart"
            ),
        ),
    ]
