# Generated by Django 4.2.6 on 2023-11-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopping_cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_shopping_cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец корзины покупок",
            ),
        ),
        migrations.AddConstraint(
            model_name="shopping_cart",
            constraint=models.UniqueConstraint(
                fields=("user", "bot"), name="unique_in_shopping_cart"
            ),
        ),
    ]
